# Teclado ABNT2 no modo gráfico (o console usa br-abnt2 pelo S30minivideo)
Section "InputClass"
    Identifier "teclado ABNT2"
    MatchIsKeyboard "on"
    Option "XkbLayout" "br"
    Option "XkbModel" "abnt2"
EndSection
